# Generated by Django 4.1 on 2022-08-30 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='trainer_media/profile')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('website', models.CharField(max_length=24)),
                ('branding_image', models.ImageField(default='default.jpg', upload_to='trainer_media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36)),
                ('free_plan', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('diet_type', models.CharField(max_length=20)),
                ('meal_type', models.CharField(max_length=20)),
                ('image', models.ImageField(default='default.jpg', upload_to='trainer_media/meals')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.trainerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='trainer_media/meals')),
                ('meal_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.mealplan')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='trainer_media/meals/food')),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('calories', models.FloatField()),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.meal')),
            ],
        ),
    ]
