# Generated by Django 4.1 on 2022-08-31 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36)),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('includes', models.TextField()),
                ('how_it_works', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='trainer_media/billing')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.trainerprofile')),
            ],
        ),
    ]
