# Generated by Django 4.1 on 2022-08-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_remove_trainerprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='first_name',
            field=models.CharField(default='test', max_length=10),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='last_name',
            field=models.CharField(default='test', max_length=10),
        ),
    ]
