# Generated by Django 4.1 on 2022-09-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0005_remove_trainerprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile'),
        ),
    ]
