# Generated by Django 4.1 on 2022-09-14 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_alter_planday_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planday',
            name='date',
        ),
    ]
