# Generated by Django 4.1 on 2022-09-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_remove_planday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='planday',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
