# Generated by Django 4.1 on 2022-09-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_planday_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planday',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
