# Generated by Django 4.1 on 2022-09-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0012_meal_calories_meal_carbs_meal_fat_meal_protein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fat',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.FloatField(default=0, null=True),
        ),
    ]
