# Generated by Django 4.1 on 2022-08-31 00:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_billingplan'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField()),
                ('CustomerProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile')),
                ('billing_plan_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trainer.billingplan')),
            ],
        ),
    ]
